language: bash
script:
  - sudo apt update
  - sudo apt install snapd locales
  - sudo locale-gen "en_US.UTF-8"
  - sudo update-locale LC_ALL="en_US.UTF-8"
  - sudo snap install tree
  - .github/tree.sh
  - cat README.md
