Vagrant.configure("2") do |config|
	config.vm.define "controller" do |controller|
		controller.vm.box = "centos/7"
		controller.vm.hostname = "LAB-Controller"
		controller.vm.network "public_network", bridge: "Intel(R) I211 Gigabit Network Connection", ip: "172.17.10.120"
		controller.vm.provider "virtualbox" do |vb|
			vb.memory = "1024"
		end
		controller.vm.provision :shell, path: 'Ansible_LAB_setup.sh'
	end
	(1..3).each do |i|
	   config.vm.define "vls-node#{i}" do |node|
		   node.vm.box = "centos/7"
		   node.vm.hostname = "vls-node#{i}"
		   node.vm.network "public_network", bridge: "Intel(R) I211 Gigabit Network Connection", ip: "172.17.10.12#{i}"
		   node.vm.provider "virtualbox" do |vb|
				 vb.memory = "512"
		   	end
		end
	end
end