---
- hosts: all

  tasks:
    - name: Install Apache.
      command: yum install -quiet -y httpd httpd-devel
    - name: Copy Configuration Files
      command: > # ">" tells to automatically quote the next indented lines
        cp httpd.conf /etc/httpd/conf/httpd.conf
      command: >
        cp httpd-vhosts.conf /etc/httpd/conf/httpd-vhosts.conf
    - name: Start Apache and configure it to run at book
      command: service httpd start && chkconfig httpd on
